#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.8

before_install:
  - export DJANGO_SETTINGS_MODULE=mms.settings
  - export PYTHONPATH=$HOME/builds/easherma/mms_django
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE django;" -U postgres

script:
  - python ./mms/manage.py test
